spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: testpassword
  rsocket:
    server:
      port: 8000
  main:
    lazy-initialization: true
#  flyway:
#    baselineOnMigrate: true
#    validateOnMigrate: false